# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Project.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rProject.proto\"&\n\rsingle_string\x12\x15\n\rsingle_string\x18\x01 \x01(\t\"\x07\n\x05\x65mpty\" \n\nsuper_path\x12\x12\n\nalpha_path\x18\x01 \x01(\t24\n\x07Project\x12)\n\x10get_project_path\x12\x06.empty\x1a\x0b.super_path\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Project_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SINGLE_STRING']._serialized_start=17
  _globals['_SINGLE_STRING']._serialized_end=55
  _globals['_EMPTY']._serialized_start=57
  _globals['_EMPTY']._serialized_end=64
  _globals['_SUPER_PATH']._serialized_start=66
  _globals['_SUPER_PATH']._serialized_end=98
  _globals['_PROJECT']._serialized_start=100
  _globals['_PROJECT']._serialized_end=152
# @@protoc_insertion_point(module_scope)
